# Site settings
name: name
email: email
url: "https://greatercreater.githun.io"
description: "A blog and a portfolio"
author: "author"
title: "BlogFolio"
permalink: pretty
baseurl:"/abc"

remote_theme: lamccloskey/jekyll-theme-blogfolio

# social
github:
  username: username

twitter:
  username: username
